# Generated by Django 5.2.15 on 2026-06-19 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('type', models.CharField(choices=[('smoke', 'Smoke'), ('chemical', 'Chemical'), ('dust', 'Dust'), ('noise', 'Noise'), ('other', 'Other')], max_length=20)),
                ('severity', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lat', 'lng'], name='reports_rep_lat_1f73a2_idx'), models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'), models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx')],
            },
        ),
    ]
